#!/bin/bash
# This script filters the output data from ALF's ana.out for facilitating
# plotting the solutions of ALF tutorial

USAGE="Usage:  $0 <data file>\n\
where <data file> is generated by ana.out and the script output is <data file>_plot.\n\
This script has not been extensively tested. No warrants.\n"

if [ "$1" == "-h" -o "$1" == "--help" -o "$#" -lt 1 ] ; then
    printf "$USAGE"
    exit 0
fi

echo "Deleting $1_plot if exists."
rm -f $1"_plot"
echo "Reading $1 and printing some of its lines to $1_plot."
while read x y
do
    echo $x $y
    if (( $(echo "$x < 0.00" | sed 's/E./*10^/g' | bc -l) )) ; then
	read line
    else
	read o p best err dump
	if (( $(echo "$y == 0.00" | sed 's/E./*10^/g' | bc -l) )) ; then
            echo $x $best $err >> $1"_plot"
	fi
    fi
done < $1
